// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: todo.proto
#ifndef GRPC_todo_2eproto__INCLUDED
#define GRPC_todo_2eproto__INCLUDED

#include "todo.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace todo {

class Account final {
 public:
  static constexpr char const* service_full_name() {
    return "todo.Account";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status requestAddCategory(::grpc::ClientContext* context, const ::todo::AddCategoryRequest& request, ::todo::CodeReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>> AsyncrequestAddCategory(::grpc::ClientContext* context, const ::todo::AddCategoryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>>(AsyncrequestAddCategoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>> PrepareAsyncrequestAddCategory(::grpc::ClientContext* context, const ::todo::AddCategoryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>>(PrepareAsyncrequestAddCategoryRaw(context, request, cq));
    }
    virtual ::grpc::Status requestFetchCategory(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest& request, ::todo::CodeReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>> AsyncrequestFetchCategory(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>>(AsyncrequestFetchCategoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>> PrepareAsyncrequestFetchCategory(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>>(PrepareAsyncrequestFetchCategoryRaw(context, request, cq));
    }
    virtual ::grpc::Status requestAddTodo(::grpc::ClientContext* context, const ::todo::AddTodoRequest& request, ::todo::CodeReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>> AsyncrequestAddTodo(::grpc::ClientContext* context, const ::todo::AddTodoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>>(AsyncrequestAddTodoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>> PrepareAsyncrequestAddTodo(::grpc::ClientContext* context, const ::todo::AddTodoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>>(PrepareAsyncrequestAddTodoRaw(context, request, cq));
    }
    virtual ::grpc::Status requestUpdateTodo(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest& request, ::todo::CodeReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>> AsyncrequestUpdateTodo(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>>(AsyncrequestUpdateTodoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>> PrepareAsyncrequestUpdateTodo(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>>(PrepareAsyncrequestUpdateTodoRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void requestAddCategory(::grpc::ClientContext* context, const ::todo::AddCategoryRequest* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void requestAddCategory(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void requestAddCategory(::grpc::ClientContext* context, const ::todo::AddCategoryRequest* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void requestAddCategory(::grpc::ClientContext* context, const ::todo::AddCategoryRequest* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void requestAddCategory(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void requestAddCategory(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void requestFetchCategory(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void requestFetchCategory(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void requestFetchCategory(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void requestFetchCategory(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void requestFetchCategory(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void requestFetchCategory(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void requestAddTodo(::grpc::ClientContext* context, const ::todo::AddTodoRequest* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void requestAddTodo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void requestAddTodo(::grpc::ClientContext* context, const ::todo::AddTodoRequest* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void requestAddTodo(::grpc::ClientContext* context, const ::todo::AddTodoRequest* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void requestAddTodo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void requestAddTodo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void requestUpdateTodo(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void requestUpdateTodo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void requestUpdateTodo(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void requestUpdateTodo(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void requestUpdateTodo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void requestUpdateTodo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>* AsyncrequestAddCategoryRaw(::grpc::ClientContext* context, const ::todo::AddCategoryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>* PrepareAsyncrequestAddCategoryRaw(::grpc::ClientContext* context, const ::todo::AddCategoryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>* AsyncrequestFetchCategoryRaw(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>* PrepareAsyncrequestFetchCategoryRaw(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>* AsyncrequestAddTodoRaw(::grpc::ClientContext* context, const ::todo::AddTodoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>* PrepareAsyncrequestAddTodoRaw(::grpc::ClientContext* context, const ::todo::AddTodoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>* AsyncrequestUpdateTodoRaw(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::todo::CodeReply>* PrepareAsyncrequestUpdateTodoRaw(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status requestAddCategory(::grpc::ClientContext* context, const ::todo::AddCategoryRequest& request, ::todo::CodeReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>> AsyncrequestAddCategory(::grpc::ClientContext* context, const ::todo::AddCategoryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>>(AsyncrequestAddCategoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>> PrepareAsyncrequestAddCategory(::grpc::ClientContext* context, const ::todo::AddCategoryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>>(PrepareAsyncrequestAddCategoryRaw(context, request, cq));
    }
    ::grpc::Status requestFetchCategory(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest& request, ::todo::CodeReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>> AsyncrequestFetchCategory(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>>(AsyncrequestFetchCategoryRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>> PrepareAsyncrequestFetchCategory(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>>(PrepareAsyncrequestFetchCategoryRaw(context, request, cq));
    }
    ::grpc::Status requestAddTodo(::grpc::ClientContext* context, const ::todo::AddTodoRequest& request, ::todo::CodeReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>> AsyncrequestAddTodo(::grpc::ClientContext* context, const ::todo::AddTodoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>>(AsyncrequestAddTodoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>> PrepareAsyncrequestAddTodo(::grpc::ClientContext* context, const ::todo::AddTodoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>>(PrepareAsyncrequestAddTodoRaw(context, request, cq));
    }
    ::grpc::Status requestUpdateTodo(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest& request, ::todo::CodeReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>> AsyncrequestUpdateTodo(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>>(AsyncrequestUpdateTodoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>> PrepareAsyncrequestUpdateTodo(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>>(PrepareAsyncrequestUpdateTodoRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void requestAddCategory(::grpc::ClientContext* context, const ::todo::AddCategoryRequest* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) override;
      void requestAddCategory(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void requestAddCategory(::grpc::ClientContext* context, const ::todo::AddCategoryRequest* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void requestAddCategory(::grpc::ClientContext* context, const ::todo::AddCategoryRequest* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void requestAddCategory(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void requestAddCategory(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void requestFetchCategory(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) override;
      void requestFetchCategory(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void requestFetchCategory(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void requestFetchCategory(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void requestFetchCategory(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void requestFetchCategory(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void requestAddTodo(::grpc::ClientContext* context, const ::todo::AddTodoRequest* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) override;
      void requestAddTodo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void requestAddTodo(::grpc::ClientContext* context, const ::todo::AddTodoRequest* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void requestAddTodo(::grpc::ClientContext* context, const ::todo::AddTodoRequest* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void requestAddTodo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void requestAddTodo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void requestUpdateTodo(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) override;
      void requestUpdateTodo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void requestUpdateTodo(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void requestUpdateTodo(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void requestUpdateTodo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void requestUpdateTodo(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::todo::CodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>* AsyncrequestAddCategoryRaw(::grpc::ClientContext* context, const ::todo::AddCategoryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>* PrepareAsyncrequestAddCategoryRaw(::grpc::ClientContext* context, const ::todo::AddCategoryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>* AsyncrequestFetchCategoryRaw(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>* PrepareAsyncrequestFetchCategoryRaw(::grpc::ClientContext* context, const ::todo::FetchCategoryRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>* AsyncrequestAddTodoRaw(::grpc::ClientContext* context, const ::todo::AddTodoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>* PrepareAsyncrequestAddTodoRaw(::grpc::ClientContext* context, const ::todo::AddTodoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>* AsyncrequestUpdateTodoRaw(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::todo::CodeReply>* PrepareAsyncrequestUpdateTodoRaw(::grpc::ClientContext* context, const ::todo::UpdateTodoRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_requestAddCategory_;
    const ::grpc::internal::RpcMethod rpcmethod_requestFetchCategory_;
    const ::grpc::internal::RpcMethod rpcmethod_requestAddTodo_;
    const ::grpc::internal::RpcMethod rpcmethod_requestUpdateTodo_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status requestAddCategory(::grpc::ServerContext* context, const ::todo::AddCategoryRequest* request, ::todo::CodeReply* response);
    virtual ::grpc::Status requestFetchCategory(::grpc::ServerContext* context, const ::todo::FetchCategoryRequest* request, ::todo::CodeReply* response);
    virtual ::grpc::Status requestAddTodo(::grpc::ServerContext* context, const ::todo::AddTodoRequest* request, ::todo::CodeReply* response);
    virtual ::grpc::Status requestUpdateTodo(::grpc::ServerContext* context, const ::todo::UpdateTodoRequest* request, ::todo::CodeReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_requestAddCategory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_requestAddCategory() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_requestAddCategory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestAddCategory(::grpc::ServerContext* /*context*/, const ::todo::AddCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestAddCategory(::grpc::ServerContext* context, ::todo::AddCategoryRequest* request, ::grpc::ServerAsyncResponseWriter< ::todo::CodeReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_requestFetchCategory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_requestFetchCategory() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_requestFetchCategory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestFetchCategory(::grpc::ServerContext* /*context*/, const ::todo::FetchCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestFetchCategory(::grpc::ServerContext* context, ::todo::FetchCategoryRequest* request, ::grpc::ServerAsyncResponseWriter< ::todo::CodeReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_requestAddTodo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_requestAddTodo() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_requestAddTodo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestAddTodo(::grpc::ServerContext* /*context*/, const ::todo::AddTodoRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestAddTodo(::grpc::ServerContext* context, ::todo::AddTodoRequest* request, ::grpc::ServerAsyncResponseWriter< ::todo::CodeReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_requestUpdateTodo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_requestUpdateTodo() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_requestUpdateTodo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUpdateTodo(::grpc::ServerContext* /*context*/, const ::todo::UpdateTodoRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestUpdateTodo(::grpc::ServerContext* context, ::todo::UpdateTodoRequest* request, ::grpc::ServerAsyncResponseWriter< ::todo::CodeReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_requestAddCategory<WithAsyncMethod_requestFetchCategory<WithAsyncMethod_requestAddTodo<WithAsyncMethod_requestUpdateTodo<Service > > > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_requestAddCategory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_requestAddCategory() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::todo::AddCategoryRequest, ::todo::CodeReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::todo::AddCategoryRequest* request, ::todo::CodeReply* response) { return this->requestAddCategory(context, request, response); }));}
    void SetMessageAllocatorFor_requestAddCategory(
        ::grpc::experimental::MessageAllocator< ::todo::AddCategoryRequest, ::todo::CodeReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::todo::AddCategoryRequest, ::todo::CodeReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_requestAddCategory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestAddCategory(::grpc::ServerContext* /*context*/, const ::todo::AddCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* requestAddCategory(
      ::grpc::CallbackServerContext* /*context*/, const ::todo::AddCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* requestAddCategory(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::todo::AddCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_requestFetchCategory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_requestFetchCategory() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::todo::FetchCategoryRequest, ::todo::CodeReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::todo::FetchCategoryRequest* request, ::todo::CodeReply* response) { return this->requestFetchCategory(context, request, response); }));}
    void SetMessageAllocatorFor_requestFetchCategory(
        ::grpc::experimental::MessageAllocator< ::todo::FetchCategoryRequest, ::todo::CodeReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::todo::FetchCategoryRequest, ::todo::CodeReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_requestFetchCategory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestFetchCategory(::grpc::ServerContext* /*context*/, const ::todo::FetchCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* requestFetchCategory(
      ::grpc::CallbackServerContext* /*context*/, const ::todo::FetchCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* requestFetchCategory(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::todo::FetchCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_requestAddTodo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_requestAddTodo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::todo::AddTodoRequest, ::todo::CodeReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::todo::AddTodoRequest* request, ::todo::CodeReply* response) { return this->requestAddTodo(context, request, response); }));}
    void SetMessageAllocatorFor_requestAddTodo(
        ::grpc::experimental::MessageAllocator< ::todo::AddTodoRequest, ::todo::CodeReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(2);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::todo::AddTodoRequest, ::todo::CodeReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_requestAddTodo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestAddTodo(::grpc::ServerContext* /*context*/, const ::todo::AddTodoRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* requestAddTodo(
      ::grpc::CallbackServerContext* /*context*/, const ::todo::AddTodoRequest* /*request*/, ::todo::CodeReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* requestAddTodo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::todo::AddTodoRequest* /*request*/, ::todo::CodeReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_requestUpdateTodo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_requestUpdateTodo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(3,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::todo::UpdateTodoRequest, ::todo::CodeReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::todo::UpdateTodoRequest* request, ::todo::CodeReply* response) { return this->requestUpdateTodo(context, request, response); }));}
    void SetMessageAllocatorFor_requestUpdateTodo(
        ::grpc::experimental::MessageAllocator< ::todo::UpdateTodoRequest, ::todo::CodeReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(3);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::todo::UpdateTodoRequest, ::todo::CodeReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_requestUpdateTodo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUpdateTodo(::grpc::ServerContext* /*context*/, const ::todo::UpdateTodoRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* requestUpdateTodo(
      ::grpc::CallbackServerContext* /*context*/, const ::todo::UpdateTodoRequest* /*request*/, ::todo::CodeReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* requestUpdateTodo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::todo::UpdateTodoRequest* /*request*/, ::todo::CodeReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_requestAddCategory<ExperimentalWithCallbackMethod_requestFetchCategory<ExperimentalWithCallbackMethod_requestAddTodo<ExperimentalWithCallbackMethod_requestUpdateTodo<Service > > > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_requestAddCategory<ExperimentalWithCallbackMethod_requestFetchCategory<ExperimentalWithCallbackMethod_requestAddTodo<ExperimentalWithCallbackMethod_requestUpdateTodo<Service > > > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_requestAddCategory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_requestAddCategory() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_requestAddCategory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestAddCategory(::grpc::ServerContext* /*context*/, const ::todo::AddCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_requestFetchCategory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_requestFetchCategory() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_requestFetchCategory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestFetchCategory(::grpc::ServerContext* /*context*/, const ::todo::FetchCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_requestAddTodo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_requestAddTodo() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_requestAddTodo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestAddTodo(::grpc::ServerContext* /*context*/, const ::todo::AddTodoRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_requestUpdateTodo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_requestUpdateTodo() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_requestUpdateTodo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUpdateTodo(::grpc::ServerContext* /*context*/, const ::todo::UpdateTodoRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_requestAddCategory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_requestAddCategory() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_requestAddCategory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestAddCategory(::grpc::ServerContext* /*context*/, const ::todo::AddCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestAddCategory(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_requestFetchCategory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_requestFetchCategory() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_requestFetchCategory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestFetchCategory(::grpc::ServerContext* /*context*/, const ::todo::FetchCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestFetchCategory(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_requestAddTodo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_requestAddTodo() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_requestAddTodo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestAddTodo(::grpc::ServerContext* /*context*/, const ::todo::AddTodoRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestAddTodo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_requestUpdateTodo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_requestUpdateTodo() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_requestUpdateTodo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUpdateTodo(::grpc::ServerContext* /*context*/, const ::todo::UpdateTodoRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestrequestUpdateTodo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_requestAddCategory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_requestAddCategory() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->requestAddCategory(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_requestAddCategory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestAddCategory(::grpc::ServerContext* /*context*/, const ::todo::AddCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* requestAddCategory(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* requestAddCategory(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_requestFetchCategory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_requestFetchCategory() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->requestFetchCategory(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_requestFetchCategory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestFetchCategory(::grpc::ServerContext* /*context*/, const ::todo::FetchCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* requestFetchCategory(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* requestFetchCategory(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_requestAddTodo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_requestAddTodo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(2,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->requestAddTodo(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_requestAddTodo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestAddTodo(::grpc::ServerContext* /*context*/, const ::todo::AddTodoRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* requestAddTodo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* requestAddTodo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_requestUpdateTodo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_requestUpdateTodo() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(3,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->requestUpdateTodo(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_requestUpdateTodo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status requestUpdateTodo(::grpc::ServerContext* /*context*/, const ::todo::UpdateTodoRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* requestUpdateTodo(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* requestUpdateTodo(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_requestAddCategory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_requestAddCategory() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::todo::AddCategoryRequest, ::todo::CodeReply>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::todo::AddCategoryRequest, ::todo::CodeReply>* streamer) {
                       return this->StreamedrequestAddCategory(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_requestAddCategory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status requestAddCategory(::grpc::ServerContext* /*context*/, const ::todo::AddCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedrequestAddCategory(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::todo::AddCategoryRequest,::todo::CodeReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_requestFetchCategory : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_requestFetchCategory() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::todo::FetchCategoryRequest, ::todo::CodeReply>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::todo::FetchCategoryRequest, ::todo::CodeReply>* streamer) {
                       return this->StreamedrequestFetchCategory(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_requestFetchCategory() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status requestFetchCategory(::grpc::ServerContext* /*context*/, const ::todo::FetchCategoryRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedrequestFetchCategory(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::todo::FetchCategoryRequest,::todo::CodeReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_requestAddTodo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_requestAddTodo() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::todo::AddTodoRequest, ::todo::CodeReply>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::todo::AddTodoRequest, ::todo::CodeReply>* streamer) {
                       return this->StreamedrequestAddTodo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_requestAddTodo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status requestAddTodo(::grpc::ServerContext* /*context*/, const ::todo::AddTodoRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedrequestAddTodo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::todo::AddTodoRequest,::todo::CodeReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_requestUpdateTodo : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_requestUpdateTodo() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::todo::UpdateTodoRequest, ::todo::CodeReply>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::todo::UpdateTodoRequest, ::todo::CodeReply>* streamer) {
                       return this->StreamedrequestUpdateTodo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_requestUpdateTodo() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status requestUpdateTodo(::grpc::ServerContext* /*context*/, const ::todo::UpdateTodoRequest* /*request*/, ::todo::CodeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedrequestUpdateTodo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::todo::UpdateTodoRequest,::todo::CodeReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_requestAddCategory<WithStreamedUnaryMethod_requestFetchCategory<WithStreamedUnaryMethod_requestAddTodo<WithStreamedUnaryMethod_requestUpdateTodo<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_requestAddCategory<WithStreamedUnaryMethod_requestFetchCategory<WithStreamedUnaryMethod_requestAddTodo<WithStreamedUnaryMethod_requestUpdateTodo<Service > > > > StreamedService;
};

}  // namespace todo


#endif  // GRPC_todo_2eproto__INCLUDED
