version: '2'

services:
  grpcserver:
    image: grpcserver:1.0
    ports:
      - "50051:50051"
    volumes:
      - "/data/log:/data/log"
    depends_on:
      - redis
      - mysql
    command: ["./account_server"]

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./conf/redis:/etc/redis/redis.conf"
      - "./data/redis:/data/redis"
    command: ["redis-server","/etc/redis/redis.conf","--appendonly","yes"]

  mysql:
    image: mysql
    expose: 
      - "3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=test"
    volumes:
      - "./logs/mysql:/logs"
      - "./data/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
