version: '2'

services:
  grpcserver:
    image: grpcserver:1.0
    ports:
      - "50051:50051"
    volumes:
      - "/data/log:/data/log"
    depends_on:
      - redis
      - mysql
    command: ["./account_server"]

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "./conf/redis:/etc/redis/redis.conf"
      - "./data/redis:/data/redis"
    command: ["redis-server","/etc/redis/redis.conf","--appendonly","yes"]

  mysql:
    image: mysql
    expose: 
      - "3306"
    network_mode: "bridge"
    environment:
       MYSQL_ROOT_PASSWORD: "broad123"
       MYSQL_USER: 'test'
       MYSQL_PASS: 'broad123'
    restart: always 
    volumes:
      - "./logs/mysql:/logs"
      - "./conf/mysql.cnf:/etc/my.cnf"
    ports:
      - "3306:3306"
